### ISSUE TITLE
Plugin Classes not working in Python Bindings:

### ISSUE THREAD

**Issue by jofemodo** [drobilla/jalv#18]
With the latest lilv version:

```
import lilv
world = lilv.World()
world.load_all()
for i in world.get_all_plugins():
  print("{} ({}) => {}".format(i.get_name(),i.get_class().get_label(),i.get_uri()))

```
It prints "Plugin" as plugin class for all plugins found in the system.

**Comment by drobilla** [comment]
WFM

```
CS Phaser 1 with LFO (Phaser) => http://drobilla.net/plugins/fomp/cs_phaser1_lfo
Moog High-Pass Filter 1 (Highpass) => http://drobilla.net/plugins/fomp/mvchpf1
Moog Low-Pass Filter 1 (Lowpass) => http://drobilla.net/plugins/fomp/mvclpf1
```

You probably don't have the LV2 data installed correctly.  The classes are defined in lv2core.ttl and it must be present in the path and loaded for this to work.

(Also nothing to do with jalv...)

**Comment by jofemodo** [comment]
Sorry for opening the issue in the wrong repo.
Anyway, you were right and the lv2core.ttl was misplaced.
 
Thanks @drobilla ! ;-)
