### ISSUE TITLE
Since loading of presets with -p is undocumented...

### ISSUE THREAD

**Issue by engineeror** [drobilla/jalv#23]
...has anyone figured out how to do it? I have several presets under ~/.lv2, such as /home/user/.lv2/EQ10Q_Stereo_headphones.preset.lv2 and it's available under Presets menu and I'm able to set it fine but can't figure out how to open jalv.gtk with that preset preselected. The -p arg doesn't accept anything, apparently it's some magical URI but nothing works :/

**Comment by brummer10** [comment]
the syntax is:
jalv.gtk -p preset_uri plugin_uri
so, for example loading the Munch Bass preset with Calf Monosynth in jalv.gtk, running:
`jalv.gtk -p http://calf.sourceforge.net/factory_presets#monosynth_MunchBass http://calf.sourceforge.net/plugins/Monosynth`

**Comment by drobilla** [comment]
Closing this since it's a question (and it's not "undocumented").  Please open a concrete issue if you have suggestions.
