### ISSUE TITLE
When running Jalv without arguments, show a dialog for LV2 plugin selection

### ISSUE THREAD

**Issue by fpesari** [drobilla/jalv#27]
Right now, running Jalv without any arguments returns this message:

```
Missing plugin URI, try lv2ls to list plugins
```

It could be made to prompt instead a dialog with a combo box which allows selection of LV2 plugins installed, instead of relying on an external program which isn't always a dependency (on Debian, it's included in the `lilv-utils` package, but many people might know how to find it).

In short, since it already depends on lilv as a library, it could use that to offer users a visual way to choose LV2 plugins. This would also allow Jalv to have its own .desktop file and to be run as a GUI application instead of a terminal application (while the previous behavior, `jalv URI`, would be left untouched).

To detect which toolkit to use to display the dialog, Jalv could try all three backends and use the first available.

**Comment by drobilla** [comment]
Added for Gtk in a42336f.
