### ISSUE TITLE
LV2 Port-group labels

### ISSUE THREAD

**Issue by x42** [drobilla/jalv#28]
jalv-qt uses lv2:name for port-groups (here control-groups):
https://github.com/drobilla/jalv/blob/87416aca2e6bedc8745a613a8bd09bf8c1cc9ee1/src/jalv_qt.cpp#L639-L645

While the port-group spec uses `rdfs:label` throughout:
https://github.com/drobilla/lv2/blob/master/lv2/port-groups/port-groups.ttl

If I understand correctly `lv2:name` is-a DatatypeProperty, port-groups are no data-types, and hence jalv should use  `LILV_NS_RDFS "label"` for the display name. Is that correct?

**Comment by drobilla** [comment]
"DatatypeProperty" means a property with a data (literal) value.  This is a DatatypeProperty because the value is a string.

**Comment by drobilla** [comment]
This might originate from my mistake in MDA, which also uses lv2:name.

**Comment by drobilla** [comment]
Fixed in 4f43777, thanks.
