### ISSUE TITLE
Have an option to make jalv generate a desktop entry

### ISSUE THREAD

**Issue by terencode** [drobilla/jalv#29]
This would be useful if you want a quick way to launch a graphical lv2 plugin. 
Something along `jalv --ui="gtk" --desktop-file URI`  which would save the .desktop under `$XDG_DATA_HOME  /applications/jalv/` by default.

**Comment by drobilla** [comment]
Hm, interesting idea.  It's a bit strange, but seems like a nice way to "appify" plugins without having to do any work.

Probably makes more sense as a script though?  I suspect that making this work well would require some additional options that don't fit so we'll in jalv itself, and adding a `jalv_make_desktop_entry.py` and shipping it with jalv would be easy.

**Comment by terencode** [comment]
Yes I agree, I'll try to write something and make a PR.

**Comment by drobilla** [comment]
Let's say b8a68cb is close enough.
