### ISSUE TITLE
jalv_ui_resize is defined but not used

### ISSUE THREAD

**Issue by yurivict** [drobilla/jalv#3]
This is just an observation that jalv_ui_resize is defined for various UI types but isn't actually used anywhere. Maybe it has to be used or deleted?

**Comment by drobilla** [comment]
I didn't really figure out exactly what happened here, but this was super old and I always thought it was a kludge anyway, so... bye! 8311df91cc212adf3220acfcb50ab63414fe9dd6

Thanks
