### ISSUE TITLE
jalv_qt missing call to jalv_init_ui(jalv);

### ISSUE THREAD

**Issue by brummer10** [drobilla/jalv#34]
I played with the latest suil from git to checkout your resize fixes. There-while I noticed that the qt interface didn't send the initial port values to the plugin UI. 
This could easily be fixed by adding a call to  jalv_init_ui(jalv) in the jalv_open_ui(Jalv* jalv) function in jalv_qt.cpp

**Comment by brummer10** [comment]
Just notice, the same is true for jalv_gtkmm

**Comment by drobilla** [comment]
367e3cb (not especially tested), thanks.
