### ISSUE TITLE
[Question] (Re)Licensing 

### ISSUE THREAD

**Issue by brummer10** [drobilla/jalv#39]
I work on a project licensed under the  0BSD License and I like to use some jalv code within it. 
Now, the  ISC License isn't compatible with the 0BSD License, so I like to ask if you could/would give me permission to use some jalv code under a relicensed  0BSD License.

**Comment by drobilla** [comment]
This is an unusual license, I'd never even heard of it before.  As far as I can tell it hasn't been vetted by anyone reputable (most notably the FSF).  Why do you say it "isn't compatible"?

In any case, it seems to be ISC with the usual attribution requirement removed for some reason.  Essentially, then, you are asking me to remove my attribution, so that depends on exactly which code you mean.

**Comment by brummer10** [comment]
I'm interested in parts to load LV2 plugins and show/communicate with there GUI, which I'll rework to fit my needs.
I don't want to remove your attribution, but when I include some parts of your code, I cant guarantee that someone else remove it, as the 0BSD explicit allow that. Hence I say it isn't compatible. It is surely compatible for linking.

**Comment by drobilla** [comment]
They are compatible in every "mechanical" sense, as far as I can tell, except the attribution one.  Having to write everything yourself is the cost of demanding everything use the same license, particularly if it's a weird one that does not adhere to the requirements of nearly every permissive license in the world.  i.e. you are literally just asking me to remove my attribution, there is no technical problem here.

Anyway, I mean specifically.  I can't grant you a blanket license to take whatever code and relicense it.  You will have to show me exactly what code you want to relicense and I can decide then, and if I agree, it will apply to only that code.  If it's just a few snippets here and there I'll probably be fine with it, if you're asking me to relicense all of jalv under this license, the answer's no.

**Comment by brummer10** [comment]
Okay, fair enough. I'll come back when I've worked it out.

**Comment by brummer10** [comment]
I'll go a other route, so I close this issue here.
Thanks so far.
