### ISSUE TITLE
jalv.gtk3 calls void (*port_event) with port_index = 1.0f (0x3f800000)

### ISSUE THREAD

**Issue by sjaehn** [drobilla/jalv#46]
jalv.gtk3 (1.6.4) calls X11 plugin (B.Oops) `void port_event(LV2UI_Handle ui, uint32_t port_index, uint32_t buffer_size, uint32_t format, const void* buffer)` with port_index = 0x3f800000 (= 1.0f).

This happened to me in very rare cases. Only with jalv but not with other hosts yet.  See https://github.com/sjaehn/BOops/issues/13 . Only just after loading / changing a preset. I've seen it with no other of my plugins. And even with B.Oops only in rare cases. Sorry, I didn't use the latest jalv release. And only incomplete debug symbols. Do you have an idea? I try to get more information in the meantime.

**Comment by sjaehn** [comment]
I tried to reproduce this bug with the actual jalv master and debugging symbols. But now it doesn't happen anymore. I started it more than 100 times. Seem like it is fixed already. Anyway, I'll also check for invalid port numbers in B.Oops from now on.

**Comment by drobilla** [comment]
I can't see a code path where this would happen directly.  Maybe it is a ring overflow, that would explain the rarity.  There's some patches for better error handling for that floating around here somewhere...

**Comment by sjaehn** [comment]
Sorry, I've to re-open it. This time I successfully caught the core dump with the current jalv master and debug symbols. But this time the port_index is valid but buffer is nullptr: https://github.com/sjaehn/BOops/issues/13

This happens (rarely) if I load or change a preset. And if I catch invalid port_event and buffer data (and print to stderr as in my current B.Oops master) then I get an endless list of non-sense like this:
```
...
BOops.lv2#GUI: Invalid control port 150994944 in BOopsGUI::port_event()
BOops.lv2#GUI: Invalid control port 905969664 in BOopsGUI::port_event()
BOops.lv2#GUI: Invalid control port 100663296 in BOopsGUI::port_event()
BOops.lv2#GUI: Invalid control port 1006632960 in BOopsGUI::port_event()
BOops.lv2#GUI: Invalid control port 0 in BOopsGUI::port_event()
BOops.lv2#GUI: Invalid control port 0 in BOopsGUI::port_event()
BOops.lv2#GUI: Invalid control port 0 in BOopsGUI::port_event()
BOops.lv2#GUI: Invalid control port 4161536 in BOopsGUI::port_event()
BOops.lv2#GUI: Invalid control port 0 in BOopsGUI::port_event()
BOops.lv2#GUI: Invalid control port 150994944 in BOopsGUI::port_event()
BOops.lv2#GUI: Invalid control port 905969664 in BOopsGUI::port_event()
BOops.lv2#GUI: Invalid control port 1006632960 in BOopsGUI::port_event()
BOops.lv2#GUI: Invalid control port 0 in BOopsGUI::port_event()
BOops.lv2#GUI: Invalid control port 0 in BOopsGUI::port_event()
BOops.lv2#GUI: Invalid control port 0 in BOopsGUI::port_event()
BOops.lv2#GUI: Invalid control port 4161536 in BOopsGUI::port_event()
BOops.lv2#GUI: Invalid control port 0 in BOopsGUI::port_event()
BOops.lv2#GUI: Invalid control port 150994944 in BOopsGUI::port_event()
BOops.lv2#GUI: Invalid control port 905969664 in BOopsGUI::port_event()
BOops.lv2#GUI: Invalid control port 1006632960 in BOopsGUI::port_event()
BOops.lv2#GUI: Invalid control port 0 in BOopsGUI::port_event()
BOops.lv2#GUI: Invalid control port 0 in BOopsGUI::port_event()
BOops.lv2#GUI: Invalid control port 0 in BOopsGUI::port_event()
BOops.lv2#GUI: Invalid control port 4161536 in BOopsGUI::port_event()
BOops.lv2#GUI: Invalid control port 0 in BOopsGUI::port_event()
BOops.lv2#GUI: Invalid control port 150994944 in BOopsGUI::port_event()
BOops.lv2#GUI: Invalid control port 905969664 in BOopsGUI::port_event()
BOops.lv2#GUI: Invalid control port 1006632960 in BOopsGUI::port_event()
...
```

At present, I've really no idea about the cause of the problems. Jalv or B.Oops or sth. else. Therefore I don't know where is the right place for this issue.

**Comment by drobilla** [comment]
I'm guessing it will go away if you crank up the ring size with `-b`

**Comment by sjaehn** [comment]
Makes sense. I'll take this flag along for testing.
