### ISSUE TITLE
jalv.gtkmm shows one "Close" button and hangs on many LV2 plugins

### ISSUE THREAD

**Issue by yurivict** [drobilla/jalv#48]
jalv.qt5 works, but jalv.gtkmm doesn't, see the video:

https://user-images.githubusercontent.com/271906/113814701-e4e9a180-9726-11eb-9a00-10a581795864.mp4

FreeBSD 12.2

**Comment by drobilla** [comment]
I feel like keeping that version around is more harm than good at this point, so "fixed" with the nuclear option: 227b485
