### ISSUE TITLE
jack_recompute_total_latencies() is called in the process callback

### ISSUE THREAD

**Issue by drobilla** [drobilla/jalv#49]
... which is not allowed.  See discussion at https://github.com/sjaehn/BSchaffl/issues/17

Original code from cebeaf2.

This event will need to be shunted to the UI thread and dealt with later somehow, though I don't know exactly how to do this correctly (or if it's even possible to do correctly, for some sufficiently pedantic definition of "correctly").

**Comment by x42** [comment]
Ardour starts a background thread for interacting with jack1. Its only job is to make or break connections and send latency-callbacks.

**Comment by drobilla** [comment]
yaaaay :/

**Comment by drobilla** [comment]
Fixed in fb19280.  There's now a generic message mechanism between the process thread and UI, so I used that to send a latency update request to the UI.

I tested that it does actually end up calling `jack_recompute_total_latencies()`, but I haven't "actually" tested this in a setup with latency compensation.
