### ISSUE TITLE
Preset confusion - how to recall saved presets?

### ISSUE THREAD

**Issue by mervinbeng** [drobilla/jalv#52]
Thanks for creating jalv. I'm trying it with DragonFly Reverb and pipewire, hoping to build a config where I can leave out the DAW.

How to I recall presets that I have saved? I know that I can start up jalv with -l <preset> to recall a saved preset, but I also want to recall the other presets via the "Presets" menu button. Even if I save several presets, the next time I fire up the plugin (using jalv.gtk3), there are no saved presets to be seen.

Separately, "Presets" on jalv.qt5 does not have any submenu items.

I'm using arch linux.

**Comment by drobilla** [comment]
When you save a preset, it should be saved as a bundle in `~/.lv2` with (approximately) the name you gave.  Are your saved presets showing up there?

Have you done anything weird with `LV2_PATH`?

**Comment by mervinbeng** [comment]
Thanks David.

$ echo $LV2_PATH
/home/mervin/.lv2:/usr/lib/lv2:/usr/local/lib/lv2

(I'm not sure where this is set.)

I don't have a ~/.lv2 . My presets are saved in ~/ (or wherever I've chosen on the file chooser)
Dragonfly_Hall_Reverb_default.preset.lv2  
Dragonfly_Hall_Reverb_test.preset.lv2
Dragonfly_Hall_Reverb_dry.preset.lv2
Dragonfly_Hall_Reverb_null.preset.lv2

These were generated on the .gtk3 version of jalv.

I am able to save state, and start up from that saved state. However, the other presets I've created won't be found. What I'd like is to be able to see the other presets, so that I can switch around during a session.

**Comment by drobilla** [comment]
Presets are just LV2 bundles like any other, so if they aren't in LV2_PATH, they will not be found.

**Comment by mervinbeng** [comment]
Ok, thanks. I've moved the *.lv2 to ~/.lv2, and I see presets on starting up!
