### ISSUE TITLE
compilation fails because of sphinx?

### ISSUE THREAD

**Issue by marclava** [drobilla/jalv#57]
git commit: d7266c6dc23c680344383ed5f15e96eaa169ba95

system: Ubuntu 20.04 LTS

sphinx version: 5.3.0
sphinx-lv2-theme version: 1.2.0

commands:
` CC=clang CXX=clang++ CXXFLAGS='-std=c++17 -Wno-error' meson setup build 
 cd build/
 meson configure
  meson compile
`
errors:
`[203/235] Generating singlehtml with a custom command
FAILED: subprojects/zix/doc/singlehtml 
/home/marc/.local/bin/sphinx-build -M singlehtml subprojects/zix/doc subprojects/zix/doc -t singlehtml -D release=0.3.1 -E -W -a -q

Warning, treated as error:
/home/marc/lv2/jalv/build/subprojects/zix/doc/api/zix_hash.rst:79:Invalid C declaration: Expected identifier in nested name, got keyword: typedef [error at 13]
  const typedef ZixHashKey *(* ZixKeyFunc)(const ZixHashRecord *record)
  -------------^
[205/235] Generating html with a custom command
FAILED: subprojects/zix/doc/html 
/home/marc/.local/bin/sphinx-build -M html subprojects/zix/doc subprojects/zix/doc -t html -D release=0.3.1 -E -W -a -q

Warning, treated as error:
/home/marc/lv2/jalv/build/subprojects/zix/doc/api/zix_hash.rst:79:Invalid C declaration: Expected identifier in nested name, got keyword: typedef [error at 13]
  const typedef ZixHashKey *(* ZixKeyFunc)(const ZixHashRecord *record)
  -------------^
[216/235] Generating html with a custom command
/home/marc/lv2/jalv/build/subprojects/lilv/doc/c/api/lilv_state.rst:6: WARNING: Invalid C declaration: Expected identifier in nested name, got keyword: typedef [error at 13]
  const typedef void*(* LilvGetPortValueFunc) (const char *port_symbol, void *user_data, uint32_t *size, uint32_t *type)
  -------------^
/home/marc/lv2/jalv/build/subprojects/lilv/doc/c/api/lilv_state.rst:80: WARNING: c:identifier cible de référence non trouvée : LilvGetPortValueFunc
[217/235] Generating singlehtml with a custom command
/home/marc/lv2/jalv/build/subprojects/lilv/doc/c/api/lilv_state.rst:6: WARNING: Invalid C declaration: Expected identifier in nested name, got keyword: typedef [error at 13]
  const typedef void*(* LilvGetPortValueFunc) (const char *port_symbol, void *user_data, uint32_t *size, uint32_t *type)
  -------------^
/home/marc/lv2/jalv/build/subprojects/lilv/doc/c/api/lilv_state.rst:80: WARNING: c:identifier cible de référence non trouvée : LilvGetPortValueFunc
[220/235] Generating book.html with a custom command
ninja: build stopped: subcommand failed.
`

**Comment by drobilla** [comment]
It hadn't occurred to me that I'd be causing people to test the subproject fallback since zix doesn't tend to be installed.

Although I'm curious why that documentation build is failing for you, in this case I think jalv should just disable all the superfluous stuff anyway.

"Fixed" by doing so in 169defc, thanks.

**Comment by drobilla** [comment]
With current zix git master, f85870e15491cc98f8a0fa247d79073e98f1694e, I get the above-mentioned prototype as expected without "typedef", like:

    .. c:type:: const ZixHashKey *(*ZixKeyFunc)(const ZixHashRecord *record)
    
This is with Doxygen 1.9.5, which is more or less the only other variable here.  What version of Doxygen do you have?

**Comment by marclava** [comment]
> What version of Doxygen do you have?

1.8.17; I upgraded to 1.9.12, pulled your latest commit, jalv compiled without problem, and it works!

Thanks a lot.

**Comment by marclava** [comment]
But I had to setup the build with:

CC=clang CXX=clang++ CXXFLAGS='-std=c++17 -Wno-error' meson setup build

Maybe it could be mentioned in your documentation.
