### ISSUE TITLE
Systemd service file fails with newer version of jalv

### ISSUE THREAD

**Issue by comiconomenclaturist** [drobilla/jalv#58]
I have been running Jalv v1.4.6 on a production server for a few years now and it's been great. However I had to use this specific version otherwise the systemd service won't start. I'd like to update Jalv to the latest version and use jack client names but I can't get the systemd service to start with newer versions. I think it's something to do with when running Jalv from the command line, newer versions drop you into a kind of shell after startup, so you can adjust the values, whereas v1.4.6 doesn't.

Does anyone know how to get systemd to start newer version of jalv? This is my service file. I've tried changing the type to simple, and setting RemainAfterExit=yes but the process always stops after startup.

```
[Unit]
Description=Calf Multiband Compressor hosted by Jalv
Requires=jackd.service
After=jackd.service

[Service]
LimitRTPRIO=infinity
LimitMEMLOCK=infinity
ExecStart=/usr/local/bin/jalv -l /etc/jalv/MultibandCompressor.ttl
Nice=-19
User=james
Restart=always

[Install]
WantedBy=multi-user.target
```

**Comment by drobilla** [comment]
> I think it's something to do with when running Jalv from the command line, newer versions drop you into a kind of shell after startup, so you can adjust the values, whereas v1.4.6 doesn't.

The `-i` option disables this, as described in the help.

**Comment by comiconomenclaturist** [comment]
oh wow, that was simple, thanks!
The latest version I got from the Debian package manager was 1.6.0 which doesn't seem to have `-i`
I'll download and compile the latest from here, thanks again

**Comment by drobilla** [comment]
You're welcome.

That was added in 1.6.2 (June 2019), Debian stable has 1.6.6 at the moment.  I don't "support" oldstable anymore, but it'll probably still build and run fine.
