### ISSUE TITLE
Missing plugin?

### ISSUE THREAD

**Issue by therealkitman** [drobilla/jalv#6]
Hi,

I have successfully compiled jalv from master and it 'runs' But I only get this message

```
chris@linux-c4x2:~/Downloads/git/jalv/build> ./jalv
Missing plugin URI, try lv2ls to list plugins
chris@linux-c4x2:~/Downloads/git/jalv/build>
``` 
I ran lv2ls and it does list my plugins as per my LV2_PATH. Not sure what to do from here.

Any directions?
Thanks,
Chris.

**Comment by therealkitman** [comment]
My mistake (again). The demo I saw used jalv.select to open a dialogue to select a plugin. I thought the dialogue was part of this build.

**Comment by drobilla** [comment]
`man jalv`, `jalv --help` ...

**Comment by drobilla** [comment]
n/p. It would be nice to have this in jalv itself but with ask the different UIS it's quite a bit of work.
