### ISSUE TITLE
Add support for multiple UIs

### ISSUE THREAD

**Issue by mxmilkiib** [drobilla/jalv#7]
Through Synthpod, Moony.lv2 can have [multiple UI windows per instance](https://github.com/OpenMusicKontrollers/moony.lv2/issues/3#issuecomment-338474457). Might this be possible Jalv?

**Comment by ventosus** [comment]
I've made a PR some years back for this [1]

@drobilla should I refactor the patch, is there still interest for this ?

[1] https://github.com/ventosus/jalv/commits/multiple-uis

**Comment by drobilla** [comment]
Sure.  All hosts probably need to get away from making single-ui-per-type assumptions...

**Comment by drobilla** [comment]
I'm assuming this means selecting from multiple UIs, not displaying several UIs at once (which seems out of scope for Jalv to me).  That was added in 6721ea5.
