### ISSUE TITLE
incorrect logscale mapping, off by one step

### ISSUE THREAD

**Issue by x42** [drobilla/jalv#9]
https://github.com/drobilla/jalv/blob/e7992e2c48fb558f0e58099b1e98b4d45fbb58ba/src/jalv_qt.cpp#L566

This does not  match the spec  at  http://lv2plug.in/ns/ext/port-props/#rangeSteps

```value = lower * pow(upper / lower, step / (steps - 1))```

"This value indicates into how many evenly-divided points the (control) port range should be divided for step-wise control."  note:   **points** - not steps between points, are inclusive. hence a `-1` is needed.

**Comment by x42** [comment]
All FAUST generated LV2s do have rangesteps. And now https://github.com/x42/dpl.lv2 has too.

**Comment by drobilla** [comment]
Fixed in 28f08bc, thanks.
